---
template_force: true
export_ovf: false
distro_name: win2019 # this needs to be one of the standard values see 'os_short_names' var
template_vm_name: "{{ inventory_hostname }}"
template_vm_root_disk_size: 30
template_vm_guest_id: windows9Server64Guest
template_vm_memory: 4096
template_vm_efi: false
template_vm_network_name: DPG-Sandbox
template_vm_ip_address: 192.168.16.40
template_vm_netmask: 255.255.240.0
template_vm_gateway: 192.168.16.1
template_vm_domain: sandbox.toal.ca
template_vm_dns_servers:
  - 192.168.1.1
  - 192.168.16.1
iso_file_name: '17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso' # name of the iso file, make sure it's uploaded a datastore
datastore_iso_folder: 'iso' # folder name on datastore where iso file resides
iso_image_index: '2' # put index number here from the order inside the iso, for example 1 - standard, 2 - core etc
iso_product_key: ''
vm_upgrade_powershell: false # only needed for 2008 R2
install_updates: false # it will take longer to build with the updates, set to true if you want the updates
vcenter_datacenter: SagelyDC
vcenter_cluster: HighPower
vcenter_folder: Demo
vcenter_resource_pool: ""
vcenter_datastore: SSD2TB
ansible_host: "{{ template_vm_ip_address }}"
instance_wait_connection_timeout: 1200
