---
# this update is needed to enable .NET clients to use https (tslv12) on Windows 8.1 and Windows Server 2012 R2
# see https://www.microsoft.com/en-us/download/confirmation.aspx?id=42883

- name: download hotfix
  win_get_url:
    url: '{{ dot_net_security_hotfix.url }}'
    dest: '{{ dot_net_security_hotfix_download_location }}\{{ dot_net_security_hotfix.file }}'
  register: download_hotfix
  until: download_hotfix is success
  delay: 3
  retries: 5

- block:
    - include_tasks: hotfix_ps4.yml
  rescue:
    - include_tasks: hotfix_ps3.yml
  vars:
    hotfix_download: "{{ dot_net_security_hotfix }}"
    hotfix_temp_directory: "{{ dot_net_security_hotfix_download_location }}"


- name: ensure hotfix file is removed
  win_file:
    path: '{{ dot_net_security_hotfix_download_location }}\{{ dot_net_security_hotfix.file }}'
    state: absent

- name: reboot if needed
  win_reboot:
  when: hotfix_install.reboot_required | default(False)