- name: create a vmware windows template
  hosts: windows_test
  gather_facts: False
  become: no
  # Workaround for https://github.com/ansible/ansible-runner/issues/1024
  vars:
    ansible_async_dir: '/tmp/.ansible_async'

  tasks:
    - name: "Create VMware Windows Template"
      include_role:
        name: oatakan.windows_vcenter_template
        apply:
          delegate_to: localhost