---
- name: Create a new VM from a VMWare Template
  hosts: localhost

  tasks:
    - name: Create a new VM from vCenter Template
      community.vmware.vmware_guest:
        name: win1.demo.toal.ca
        state: poweredon
        template: windows_template
        datacenter: SagelyDC
        folder: /Demo
        cluster: HighPower
        disk:
          - size_gb: 60
            type: thin
            datastore: EVO2TB
        networks:
          - name: DPG-Sandbox
        hardware:
          memory_mb: 4096
          num_cpus: 2
          # scsi: paravirtual
        wait_for_ip_address: true
      delegate_to: localhost
      register: deploy
