---
- name: Add host
  hosts: localhost
  vars:
    newhost: win1.demo.toal.ca

  tasks:
    - name: Add new hosts to inventory
      ansible.builtin.add_host:
        name: "{{ newhost }}"
        groups:
          - windows
          - new_hosts

- name: Create a new VM from a VMWare Template
  hosts: new_hosts
  gather_facts: false
  tasks:
    - name: Create a new VM from vCenter Template
      community.vmware.vmware_guest:
        name: "{{ inventory_hostname }}"
        state: poweredon
        template: windows_template
        datacenter: SagelyDC
        folder: /Demo
        cluster: HighPower
        disk:
          - size_gb: 60
            type: thin
            datastore: EVO2TB
        networks:
          - name: DPG-Sandbox
        hardware:
          memory_mb: 4096
          num_cpus: 2
          # scsi: paravirtual
        wait_for_ip_address: true
        customization:
          autologon: true
          autologoncount: 3
          orgname: ansible
          fullname: ansible
          existing_vm: true
          password: "{{ ansible_password }}"
          runonce:
            - cmd.exe /C powershell.exe -command "& $([scriptblock]::Create((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1'))) -ForceNewSSLCert -EnableCredSSP"
            - winrm set winrm/config/service/auth @{CredSSP="true"}
            - netsh advfirewall set allprofiles state off
        wait_for_customization: true
        wait_for_customization_timeout: 600
      delegate_to: localhost
      register: deploy
