---

- block:
    - name: ensure Windows ADK with DISM is installed
      win_package:
        path: https://go.microsoft.com/fwlink/?linkid=873065 # version 10.0.17134.0
        product_id: '{d794748d-72e9-45d7-9ab7-83d6c4c80f7f}'
        expected_return_code:
          - 0
          - 3010
        arguments: /quiet /norestart /features OptionId.DeploymentTools OptionId.WindowsPreinstallationEnvironment OptionId.ImagingAndConfigurationDesigner OptionId.UserStateMigrationTool
      notify:
        - get Windows ADK uninstall command
        - uninstall Windows ADK
  rescue:
    - name: ensure Windows ADK with DISM is installed (chocolatey)
      win_chocolatey:
        name: windows-adk-deploy
        state: present
        version: 10.0.17134.0
      register: install_windows_adk_deploy
      notify: ensure Windows ADK with DISM is removed

- block:
    - name: download hotfix
      win_get_url:
        url: '{{ win_61_security_hot_fix.url }}'
        dest: '{{ temp_directory }}\{{ win_61_security_hot_fix.file }}'
      register: download_hotfix
      until: download_hotfix is success
      delay: 3
      retries: 5

    - include_tasks: hotfix_ps3.yml
      when: ansible_powershell_version is version('3', '==')
      vars:
        hotfix_download: "{{ win_61_security_hot_fix }}"
        hotfix_temp_directory: "{{ temp_directory }}"

    - include_tasks: hotfix_ps4.yml
      when: ansible_powershell_version is version('4', '>=')
      vars:
        hotfix_download: "{{ win_61_security_hot_fix }}"
        hotfix_temp_directory: "{{ temp_directory }}"

    - name: reboot
      win_reboot:
      when:
        - hotfix_install is defined
        - hotfix_install is changed
  always:
    - name: ensure hotfix file is removed
      win_file:
        path: '{{ temp_directory }}\{{ win_61_security_hot_fix.file }}'
        state: absent